### ISSUE TITLE
Enhancement: store users' informations

### ISSUE THREAD

**Issue by jchout** [RaviG76/payroll-zen-html#9]
When a register in /inscription.html, the informations must be stored in a CSV file for future use (ex: mailchimp).

![image](https://cloud.githubusercontent.com/assets/7809189/6416290/655ac22e-bea5-11e4-9e4c-bcad6ec74625.png)

**Comment by ghost** [comment]
Enhancement: store users' informations

**Comment by RaviG76** [comment]
I have stored Email in CSV file(file.csv)
